# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipephoto',
            name='owner',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='RecipePhoto',
        ),
    ]
